### ISSUE TITLE
gff_to_jsonl.py error

### ISSUE THREAD

**Issue by aminakur** [higlass/gene_annotations#1]
I am getting an error when trying to create a gene annotations file from GFF 

```
Processing line #: 0
Traceback (most recent call last):
  File "scripts/gff_to_jsonl.py", line 116, in <module>
    main()
  File "scripts/gff_to_jsonl.py", line 84, in main
    for p in parts["attributes"].strip(";").split(";")
KeyError: 'attributes'
```

**Comment by DaydreamingElephant** [comment]
Hello! You probably have .gbff format file.
